# CONFIG TK
FONT_FAMILY = "Times"

FONT_TIMES_12 = (FONT_FAMILY, 12)
FONT_TIMES_14 = (FONT_FAMILY, 14)
FONT_TIMES_15 = (FONT_FAMILY, 15)

WHITE_COLOR = "#FFFFFF"
BLACK_COLOR = "#000000"
RED_COLOR = "#FF0000"
GREEN_COLOR = "#00FF00"

RELIEF_RAISED = "raised"

ANCHOR_CENTER = "center"
